### ISSUE TITLE
Create executable for MS Windows

### ISSUE THREAD

**Issue by Motorrat** [Motorrat/anonyxel#1]
ToDo.

**Comment by Motorrat** [comment]
Pyinstall could be just enough. Use anonyxel_cmd.py

**Comment by d2k** [comment]
please add  package  xlwt to the required package list

it currently states 
# python3.6
#pip install pandas xlrd openpyxl sklearn tables

works now with windows10

**Comment by Motorrat** [comment]
added package xlwt to the comment inline
